version: 2
updates:

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Kolkata"
    target-branch: "task/dependabot"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "php"
      - "laravel"
    commit-message:
      prefix: "chore(composer)"
    ignore:
      - dependency-name: "laravel/framework"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Kolkata"
    target-branch: "task/dependabot"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "javascript"
      - "reactjs"
    commit-message:
      prefix: "chore(npm)"
    ignore:
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Kolkata"
    target-branch: "task/dependabot"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(actions)"
